version: 2
jobs:
  build-node-common: &common-build
    docker:
      # The docker section here is not used, but required
      - image: circleci/node:6.0.0
    
    working_directory: ~/repo

    steps:
      - checkout
      
      - run: npm install

      - run: npm run lint

      - run: npm test

  build-6.12.2:
    <<: *common-build
    docker:
      # Travis was using Node.js v5.12.0 which CircleCI does have, therefore use closest match
      - image: circleci/node:6.12.2

  build-8.9.3:
    <<: *common-build
    docker:
      - image: circleci/node:8.9.3

workflows:
  version: 2
  build_all:
    jobs:
      - build-6.12.2
      - build-8.9.3
